name: 编译 OpenWrt 并上传固件
on: push
  #  repository_dispatch:
  # workflow_dispatch:

jobs:
  openwrt-build:
    name: OpenWrt 编译
    runs-on: ubuntu-24.04

    steps:
    - name: 读取 config 配置文件
      uses: actions/checkout@v4

    - name: 安装编译环境
      id: init
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -y update
        sudo -E apt-get -y install build-essential clang flex bison g++ gawk \
          gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
          python3-setuptools rsync swig unzip zlib1g-dev file wget
        sudo timedatectl set-timezone "Asia/Shanghai"

    - name: 获取系统信息
      run: |
        echo "===================="
        echo "$(id)"
        echo "系统核心个数: $(nproc)"
        echo "当前工作目录: $(pwd)"
        echo "当前目录内容:"
        ls -aFhl
        echo "===================="

    - name: 克隆 openwrt
      run: |
        git clone https://git.openwrt.org/openwrt/openwrt.git
        cd openwrt/
        git switch v24.10.0 --detach

    - name: 更新订阅内容和配置文件
      run: |
        cp custom/.config openwrt/.config
        ./feeds/argon-theme.sh
        ./feeds/openclash.sh

    - name: 更新并安装 openwrt 包
      run: |
        cd openwrt/
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: 开始编译 openwrt
      run: |
        cd openwrt/
        git branch
        make defconfig
        make -j$(nproc)

    - name: 测试
      run: |
        cd openwrt/
        echo "===================="
        echo "当前工作目录: $(pwd)"
        echo "当前目录内容:"
        ls -aFhl
        echo "===================="
